apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-credentials
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: {{ .Values.mongodb.auth.secretName }}
    creationPolicy: Owner
  
  data:
    - secretKey: username
      remoteRef:
        key: mongodb-credentials
        property: username
      
    - secretKey: password
      remoteRef:
        key: mongodb-credentials
        property: password
    
    - secretKey: MONGO_URI
      remoteRef:
        key: mongodb-credentials
        property: MONGO_URI