apiVersion: v1
kind: Service
metadata:
    name: frontend-service
    namespace: {{ .Values.namespace }}
    labels:
      app: frontend
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.port }}