apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: mongodb
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mongodb.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mongodb.storage.size }}